using ImGuiBindingsGenerator.Models;

namespace ImGuiBindingsGenerator.Generators;

/// <summary>
/// Generates C# constants from #define macros.
/// </summary>
public sealed class ConstantGenerator
{
    private readonly GeneratorConfig _config;
    private readonly ConditionalEvaluator _condEval;

    public ConstantGenerator(GeneratorConfig config, ConditionalEvaluator condEval)
    {
        _config = config;
        _condEval = condEval;
    }

    public string Generate(List<DefineItem> defines)
    {
        var w = new CodeWriter();
        w.WriteLine("// Auto-generated by ImGuiBindingsGenerator");
        w.WriteLine($"namespace {_config.Namespace};");
        w.WriteLine();
        w.WriteLine("public static partial class ImGuiConstants");
        w.OpenBrace();

        foreach (var define in defines)
        {
            if (!_condEval.ShouldInclude(define.Conditionals))
                continue;

            if (string.IsNullOrEmpty(define.Content))
                continue;

            var name = define.Name;
            var content = define.Content.Trim();

            // Skip macros that are not simple values
            if (content.Contains('(') && !content.StartsWith('('))
                continue;

            // Determine value type and emit
            var (csType, csValue) = ParseDefineValue(content);
            if (csType == null)
                continue;

            w.WriteLine($"public const {csType} {name} = {csValue};");
        }

        w.CloseBrace();
        return w.ToString();
    }

    private static (string? Type, string Value) ParseDefineValue(string content)
    {
        // String literal: "1.92.7"
        if (content.StartsWith('"') && content.EndsWith('"'))
            return ("string", content);

        // Try parse as integer
        if (TryParseInteger(content, out var intVal))
            return ("int", intVal.ToString());

        // Hex literal
        if (content.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
        {
            // Check if it fits in int (may be unsigned)
            if (content.Length <= 10) // 0x + 8 hex digits
                return ("int", $"unchecked((int){content})");
            return ("long", $"unchecked((long){content})");
        }

        // Skip values that reference other macros/identifiers (not resolvable as constants)
        // e.g., IM_COUNTOF, IM_ARRAYSIZE = IM_COUNTOF
        // Check this early to avoid false matches (e.g., identifier ending with 'F' matching float check)
        if (content.All(c => char.IsLetterOrDigit(c) || c == '_') && content.Any(char.IsLetter))
        {
            // It's a single identifier — skip it as it's a macro alias
            return (null, content);
        }

        // Float literal
        if (content.EndsWith('f') || content.EndsWith('F') || content.Contains('.'))
        {
            return ("float", content.EndsWith('f') || content.EndsWith('F') ? content : content + "f");
        }

        // Empty define or flag-style (no value)
        if (content is "" or "1")
            return (null, "");

        return (null, content);
    }

    private static bool TryParseInteger(string s, out long value)
    {
        // Handle parenthesized expressions
        s = s.Trim();
        if (s.StartsWith('(') && s.EndsWith(')'))
            s = s[1..^1].Trim();

        return long.TryParse(s, out value);
    }
}
