using ImGuiBindingsGenerator.Models;

namespace ImGuiBindingsGenerator.Generators;

/// <summary>
/// Generates C# delegate types from function pointer typedefs and struct fields.
/// </summary>
public sealed class DelegateGenerator
{
    private readonly GeneratorConfig _config;
    private readonly TypeResolver _typeResolver;
    private readonly ConditionalEvaluator _condEval;

    public DelegateGenerator(GeneratorConfig config, TypeResolver typeResolver, ConditionalEvaluator condEval)
    {
        _config = config;
        _typeResolver = typeResolver;
        _condEval = condEval;
    }

    public string Generate(List<TypedefItem> typedefs, IReadOnlyList<DelegateInfo> additionalDelegates)
    {
        var w = new CodeWriter();
        w.WriteLine("// Auto-generated by ImGuiBindingsGenerator");
        w.WriteLine("using System.Runtime.InteropServices;");
        w.WriteLine();
        w.WriteLine($"namespace {_config.Namespace};");
        w.WriteLine();

        // Generate delegates from function pointer typedefs
        foreach (var typedef in typedefs)
        {
            if (!_condEval.ShouldInclude(typedef.Conditionals))
                continue;

            var delegateInfo = _typeResolver.ResolveFunctionPointerTypedef(typedef);
            if (delegateInfo == null)
                continue;

            GenerateDelegate(w, delegateInfo, typedef.Comments);
            w.WriteLine();
        }

        // Generate delegates discovered in struct fields
        foreach (var delegateInfo in additionalDelegates)
        {
            GenerateDelegate(w, delegateInfo, null);
            w.WriteLine();
        }

        return w.ToString();
    }

    private void GenerateDelegate(CodeWriter w, DelegateInfo info, Comments? comments)
    {
        w.WriteDocComment(comments?.Preceding, comments?.Attached);

        bool hasPointers = info.Parameters.Any(p => TypeResolver.ContainsPointer(p.Type))
                        || TypeResolver.ContainsPointer(info.ReturnType);
        var unsafeModifier = hasPointers ? "unsafe " : "";

        w.WriteLine("[UnmanagedFunctionPointer(CallingConvention.Cdecl)]");

        var paramList = string.Join(", ", info.Parameters.Select(p => $"{p.Type} {p.Name}"));
        w.WriteLine($"public {unsafeModifier}delegate {info.ReturnType} {info.Name}({paramList});");
    }
}
